---
apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-example
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-example
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx-example
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: nginx-example-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: nginx-example
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: nginx-example-ingress
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  rules:
    -  http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: nginx-example-service
                port:
                  number: 80